name: "Workflow Exemplo"

on:
    workflow_dispatch:

jobs: 
    configurar:
        runs-on: ubuntu-latest
        steps:
            - name: Fazer o checkout do código
              uses: actions/checkout@v4 # essa é uma action que permite ter acesso ao código durante a execução
              with:
                ref: main # ref é um input que diz qual será o nome da branch que utilizaremos
            - name: Listar arquivos e pastas
              run: |
                ls -la
            - name: Instalar Node.JS
              uses: actions/setup-node@v4
              with:
                node-version: 22 
            - name: Instalar as dependencias
              run: npm ci
            - name: Instalar Angular CLI
              run: npm install --global @angular/cli
            - name: Build - gerar o fonte de produção
              run: ng build --configuration production --base-href=/.../
            - name: Listar arquivos e pastas
              run: |
                ls -la
            
    construir:
        runs-on: ubuntu-24.04
        needs:
            - configurar
        steps:
            - name: Instalar as dependencias
              run: echo 'Instalando as dependencias'
