name: "Workflow Exemplo"

on:
    push:
    workflow_dispatch:

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Fazer o checkout do código
              uses: actions/checkout@v4 # essa é uma action que permite ter acesso ao código durante a execução
              with:
                ref: main # ref é um input que diz qual será o nome da branch que utilizaremos
            - name: Instalar Node.JS
              uses: actions/setup-node@v4
              with:
                node-version: 22 
            - name: Instalar as dependencias
              run: npm ci
            - name: Instalar Angular CLI
              run: npm install --global @angular/cli
            - name: Build - gerar o fonte de produção
              run: ng build --configuration production --base-href=/escola-ng/
            - name: Salvar a pasta dist como artefato
              uses: actions/upload-artifact@v4
              with:
                name: build-artifact
                path: dist/
    deploy:
        runs-on: ubuntu-24.04
        needs: [build]
        steps:
            - name: Fazer o checkout do código
              uses: actions/checkout@v4 # essa é uma action que permite ter acesso ao código durante a execução
              with:
                ref: main
            - name: Download do artefato
              uses: actions/download-artifact@v4
              with:
                name: build-artifact
                path: ./dist
            - name: Configurar Git
              run: |
                git config user.name "Thomas Johannes David Weidner"
                git config user.email "thomas.jdweidner@gmail.com"
                npm install --global angular-cli-ghpages
            - name: Deploy to Github Pages
              run: npx angular-cli-ghpages --dir=dist/escola-ng/browser --no-silent
              env:
                cli: true
                GH_TOKEN: ${{ secrets.TOKEN_TO_DEPLOY }}
